export const AUTH_ERRORS = {
  INVALID_PASSWORD: "AUTH_INVALID_PASSWORD",
  USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
};

export const USER_ERRORS = {
  ALREADY_EXISTS: "USER_ALREADY_EXISTS",
};
